services:

  web1:
    build: ./web
    container_name: web1
    volumes:
      - ./web/web1:/usr/share/nginx/html:ro
    environment:
      PGHOST: db
      PGUSER: app
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: boutique
    networks: [tp-net]
    restart: unless-stopped

  web2:
    build: ./web
    container_name: web2
    volumes:
      - ./web/web2:/usr/share/nginx/html:ro
    environment:
      PGHOST: db
      PGUSER: app
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: boutique
    networks: [tp-net]
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: boutique
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [tp-net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d boutique"]
      interval: 5s
      timeout: 3s
      retries: 5

  lb:
    image: nginx:alpine
    container_name: lb
    ports:
      - "8080:80"
    volumes:
      - ./lb/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [web1, web2]
    networks: [tp-net]
    restart: unless-stopped

  backup-server:
    build:
      context: ./backup
      dockerfile: server.Dockerfile
    container_name: backup-server
    volumes:
      - backup-data:/backups
    networks: [tp-net]
    restart: unless-stopped

  backup-runner:
    build:
      context: ./backup
      dockerfile: runner.Dockerfile
    container_name: backup-runner
    environment:
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_REPOSITORY: sftp:backup@backup-server:/backups/restic-repo
      PGHOST: db
      PGUSER: app
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: boutique
    volumes:
      - ./backup/keys/id_ed25519:/root/.ssh/id_ed25519:ro
      - ./web/web1:/data/web1:ro
      - ./web/web2:/data/web2:ro
    depends_on:
      - backup-server
      - db
    networks: [tp-net]
    restart: unless-stopped

networks:
  tp-net:

volumes:
  db-data:
  backup-data:
